"""Add Review Model

Revision ID: ab36b0a8b4bb
Revises: 3a9349309f57
Create Date: 2024-03-25 06:43:42.959081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab36b0a8b4bb'
down_revision = '3a9349309f57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
